import type { Metadata } from "next";
import { BrandMark } from "@/components/brand-mark";
import { PixelMascot } from "@/components/pixel-mascot";
import { AuthForm } from "@/components/auth-form";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { hasSupabaseEnv } from "@/lib/supabase/env";
export const metadata:Metadata={title:"Entrar"};
export default async function LoginPage({searchParams}:{searchParams:Promise<{mode?:string;oauth?:string;redirectTo?:string;password?:string}>}){if(hasSupabaseEnv){const supabase=await createClient();const{data}=await supabase.auth.getUser();if(data.user)redirect("/app");}const{mode,oauth,redirectTo,password}=await searchParams;return <main className="grid min-h-screen bg-[var(--surface)] lg:grid-cols-[.9fr_1.1fr]"><section className="flex min-h-screen flex-col px-6 py-6 sm:px-12 lg:px-20"><BrandMark/><div className="mx-auto my-auto w-full max-w-md py-12"><p className="eyebrow">Seu checkpoint</p><h1 className="font-display mt-3 text-4xl font-black tracking-[-.04em]">Bom ter você de volta.</h1><p className="mt-2 text-[var(--muted)]">Entre para continuar exatamente de onde parou.</p>{password==="updated"&&<p className="mt-4 rounded-xl bg-[#e1f7ed] p-3 text-sm font-bold text-[#18734f]">Senha atualizada. Entre novamente.</p>}<div className="mt-8"><AuthForm initialMode={mode==="signup"?"signup":"login"} oauthError={oauth==="error"} redirectTo={redirectTo}/></div></div><p className="text-center text-xs text-[var(--muted)]">Use seus dados apenas neste ambiente oficial.</p></section><aside className="pixel-grid relative hidden place-items-center overflow-hidden bg-[#31294e] p-14 text-white lg:grid"><div className="relative max-w-lg"><PixelMascot/><blockquote className="font-display mt-7 text-4xl font-black leading-tight tracking-[-.04em]">“Consistência não é fazer muito. É voltar amanhã.”</blockquote><p className="mt-5 text-lg text-[#cfc9e8]">Lupi, seu parceiro nessa jornada de 100 dias.</p></div></aside></main>}
