import { Award, CheckCircle2, Flag, Flame, LockKeyhole, Medal, Mountain, Shield, Target, TimerReset, Trophy } from "lucide-react";
import { getAchievementsData, type Achievement } from "@/lib/app-data";

const icons = { flag: Flag, check: CheckCircle2, flame: Flame, target: Target, timer: TimerReset, shield: Shield, mountain: Mountain, trophy: Trophy } as const;
function unlock(value: Achievement["user_achievements"]) { return Array.isArray(value) ? value[0]?.unlocked_at : value?.unlocked_at; }

export default async function AchievementsPage() {
  const data = await getAchievementsData();
  const unlocked = data.achievements.filter((item) => unlock(item.user_achievements)).length;
  return <><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">COLEÇÃO</p><h1 className="font-display mt-2 text-3xl font-black tracking-[-.04em] md:text-4xl">Suas conquistas</h1><p className="mt-2 text-[var(--muted)]">Conquistas lidas diretamente do seu perfil.</p></div><div className="card flex items-center gap-3 px-5 py-3"><Medal className="text-[#d49400]" /><div><span className="text-xs font-bold text-[var(--muted)]">Desbloqueadas</span><strong className="font-display block text-xl">{unlocked} de {data.achievements.length}</strong></div></div></section><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data.achievements.map((item) => { const unlockedAt = unlock(item.user_achievements); const Icon = icons[item.icon as keyof typeof icons] ?? Award; return <article key={item.id} className={`card relative p-6 ${unlockedAt ? "border-[#f0d484]" : "opacity-70"}`}><span className={`grid h-14 w-14 place-items-center rounded-2xl ${unlockedAt ? "bg-[#fff4d3] text-[#d18a00]" : "bg-[var(--surface-soft)] text-[var(--muted)]"}`}>{unlockedAt ? <Icon size={28} /> : <LockKeyhole size={25} />}</span>{unlockedAt && <span className="chip absolute right-4 top-4 bg-[#e1f7ed] text-[#18734f]">Desbloqueada</span>}<h2 className="font-display mt-5 text-xl font-black">{item.name}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.description}</p><span className="mt-4 block text-xs font-bold text-[var(--muted)]">{unlockedAt ? `Conquistada em ${new Intl.DateTimeFormat("pt-BR").format(new Date(unlockedAt))}` : `Meta: ${item.condition_value}`}</span></article>; })}</section></>;
}
