"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { ArrowRight, Eye, EyeOff, LoaderCircle } from "lucide-react";
import { login, signInWithGoogle, signup, type AuthState } from "@/app/actions/auth";

const initial:AuthState={};
export function AuthForm({initialMode="login",oauthError=false}:{initialMode?:"login"|"signup";oauthError?:boolean}){const[mode,setMode]=useState(initialMode);const action=mode==="login"?login:signup;const[state,formAction,pending]=useActionState(action,initial);const[googleState,googleAction,googlePending]=useActionState(signInWithGoogle,initial);const[show,setShow]=useState(false);return <div>
  <div className="mb-7 grid grid-cols-2 rounded-xl bg-[#f0eef7] p-1" role="tablist"><button role="tab" aria-selected={mode==="login"} className={`rounded-lg py-2.5 text-sm font-extrabold ${mode==="login"?"bg-white text-[#6c4cff] shadow-sm":"text-[#716b86]"}`} onClick={()=>setMode("login")}>Entrar</button><button role="tab" aria-selected={mode==="signup"} className={`rounded-lg py-2.5 text-sm font-extrabold ${mode==="signup"?"bg-white text-[#6c4cff] shadow-sm":"text-[#716b86]"}`} onClick={()=>setMode("signup")}>Criar conta</button></div>
  <form action={formAction} className="space-y-4">{mode==="signup"&&<Field label="Seu nome" name="name" placeholder="Como podemos chamar você?" error={state?.errors?.name?.[0]}/>}<Field label="E-mail" name="email" type="email" placeholder="voce@email.com" error={state?.errors?.email?.[0]}/><div><label className="label" htmlFor="password">Senha</label><div className="relative"><input className="input pr-11" id="password" name="password" type={show?"text":"password"} placeholder="Mínimo de 8 caracteres" autoComplete={mode==="login"?"current-password":"new-password"} required/><button type="button" className="absolute right-3 top-3 text-[#716b86]" onClick={()=>setShow(!show)} aria-label={show?"Ocultar senha":"Mostrar senha"}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{state?.errors?.password?.[0]&&<p className="mt-1 text-xs font-bold text-[#c5444d]">{state.errors.password[0]}</p>}</div>
  {mode==="login"&&<div className="text-right"><Link href="/recuperar-senha" className="text-sm font-extrabold text-[#6c4cff]">Esqueci minha senha</Link></div>}{state?.message&&<p className="rounded-xl bg-[#f3f0ff] p-3 text-sm font-bold text-[#4c32ca]" aria-live="polite">{state.message}</p>}<button disabled={pending} className="btn-primary w-full" type="submit">{pending?<LoaderCircle className="animate-spin" size={18}/>:<>{mode==="login"?"Entrar na jornada":"Criar meu desafio"}<ArrowRight size={18}/></>}</button>
  </form>{mode==="signup"&&<><div className="my-5 flex items-center gap-3 text-xs font-bold text-[#aaa4bd]"><span className="h-px flex-1 bg-[#ded9ee]"/>OU CONTINUE COM<span className="h-px flex-1 bg-[#ded9ee]"/></div>{(oauthError||googleState?.message)&&<p className="mb-3 rounded-xl bg-[#fff0f1] p-3 text-sm font-bold text-[#a83741]" aria-live="polite">{googleState?.message??"Não foi possível concluir o acesso com Google. Tente novamente."}</p>}<form action={googleAction}><button disabled={googlePending} className="btn-secondary w-full border-[#d8d3e5] bg-white text-[#31294e] hover:border-[#b9b0d3]" type="submit">{googlePending?<LoaderCircle className="animate-spin" size={19}/>:<GoogleMark/>}Continuar com Google</button></form></>}{mode==="login"&&<><div className="my-5 flex items-center gap-3 text-xs font-bold text-[#aaa4bd]"><span className="h-px flex-1 bg-[#ded9ee]"/>OU<span className="h-px flex-1 bg-[#ded9ee]"/></div><Link href="/app" className="btn-secondary w-full">Explorar demonstração</Link></>}</div>}
function Field({label,name,type="text",placeholder,error}:{label:string;name:string;type?:string;placeholder:string;error?:string}){return <div><label className="label" htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} placeholder={placeholder} required/>{error&&<p className="mt-1 text-xs font-bold text-[#c5444d]">{error}</p>}</div>}
function GoogleMark(){return <svg aria-hidden="true" viewBox="0 0 24 24" className="h-[19px] w-[19px]"><path fill="#4285F4" d="M21.6 12.23c0-.71-.06-1.4-.18-2.06H12v3.9h5.38a4.6 4.6 0 0 1-2 3.02v2.53h3.24c1.9-1.75 2.98-4.33 2.98-7.39Z"/><path fill="#34A853" d="M12 22c2.7 0 4.97-.9 6.62-2.38l-3.24-2.53c-.9.6-2.05.96-3.38.96-2.6 0-4.81-1.76-5.6-4.13H3.05v2.61A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.4 13.92A6.02 6.02 0 0 1 6.08 12c0-.67.12-1.32.32-1.92V7.47H3.05A10 10 0 0 0 2 12c0 1.61.39 3.14 1.05 4.53l3.35-2.61Z"/><path fill="#EA4335" d="M12 5.95c1.47 0 2.79.5 3.82 1.5l2.87-2.87A9.61 9.61 0 0 0 12 2a10 10 0 0 0-8.95 5.47l3.35 2.61c.79-2.37 3-4.13 5.6-4.13Z"/></svg>}
