"use client";
import Link from "next/link";
import { useActionState, useState } from "react";
import { ArrowRight, Eye, EyeOff, LoaderCircle } from "lucide-react";
import { login, signup, type AuthState } from "@/app/actions/auth";

const initial:AuthState={};
export function AuthForm({initialMode="login"}:{initialMode?:"login"|"signup"}){const[mode,setMode]=useState(initialMode);const action=mode==="login"?login:signup;const[state,formAction,pending]=useActionState(action,initial);const[show,setShow]=useState(false);return <div>
  <div className="mb-7 grid grid-cols-2 rounded-xl bg-[#f0eef7] p-1" role="tablist"><button role="tab" aria-selected={mode==="login"} className={`rounded-lg py-2.5 text-sm font-extrabold ${mode==="login"?"bg-white text-[#6c4cff] shadow-sm":"text-[#716b86]"}`} onClick={()=>setMode("login")}>Entrar</button><button role="tab" aria-selected={mode==="signup"} className={`rounded-lg py-2.5 text-sm font-extrabold ${mode==="signup"?"bg-white text-[#6c4cff] shadow-sm":"text-[#716b86]"}`} onClick={()=>setMode("signup")}>Criar conta</button></div>
  <form action={formAction} className="space-y-4">{mode==="signup"&&<Field label="Seu nome" name="name" placeholder="Como podemos chamar você?" error={state?.errors?.name?.[0]}/>}<Field label="E-mail" name="email" type="email" placeholder="voce@email.com" error={state?.errors?.email?.[0]}/><div><label className="label" htmlFor="password">Senha</label><div className="relative"><input className="input pr-11" id="password" name="password" type={show?"text":"password"} placeholder="Mínimo de 8 caracteres" autoComplete={mode==="login"?"current-password":"new-password"} required/><button type="button" className="absolute right-3 top-3 text-[#716b86]" onClick={()=>setShow(!show)} aria-label={show?"Ocultar senha":"Mostrar senha"}>{show?<EyeOff size={20}/>:<Eye size={20}/>}</button></div>{state?.errors?.password?.[0]&&<p className="mt-1 text-xs font-bold text-[#c5444d]">{state.errors.password[0]}</p>}</div>
  {mode==="login"&&<div className="text-right"><Link href="/recuperar-senha" className="text-sm font-extrabold text-[#6c4cff]">Esqueci minha senha</Link></div>}{state?.message&&<p className="rounded-xl bg-[#f3f0ff] p-3 text-sm font-bold text-[#4c32ca]" aria-live="polite">{state.message}</p>}<button disabled={pending} className="btn-primary w-full" type="submit">{pending?<LoaderCircle className="animate-spin" size={18}/>:<>{mode==="login"?"Entrar na jornada":"Criar meu desafio"}<ArrowRight size={18}/></>}</button>
  </form><div className="my-5 flex items-center gap-3 text-xs font-bold text-[#aaa4bd]"><span className="h-px flex-1 bg-[#ded9ee]"/>OU<span className="h-px flex-1 bg-[#ded9ee]"/></div><Link href="/app" className="btn-secondary w-full">Explorar demonstração</Link></div>}
function Field({label,name,type="text",placeholder,error}:{label:string;name:string;type?:string;placeholder:string;error?:string}){return <div><label className="label" htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} placeholder={placeholder} required/>{error&&<p className="mt-1 text-xs font-bold text-[#c5444d]">{error}</p>}</div>}
